name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]
  # Optionally, you could also trigger on tags or pull requests

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository’s code
      - name: Check out code
        uses: actions/checkout@v2

      # Set up QEMU to enable multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # Set up Docker Buildx (provides advanced build features like multi-arch)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          # Adjust if your Dockerfile is in a different location:
          file: ./Dockerfile
          push: true
          # You can build for multiple architectures if desired (e.g., linux/arm64)
          platforms: linux/amd64
          # Set your image name and tags. Adjust as needed, e.g., version tags.
          tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/bitcoin-core-binary:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/bitcoin-core-binary:${{ github.ref_name }}
